branches:
  only:
    - master
    
environment:
  NETLIFY_TOKEN:
    secure: YlvUfYuyESNu1oO7zzqrPBZEamNz1Ss83eH82ylp1hTw6yWdlXyMCuYc1iLst2388M8kMqhBtXyTCY69h2zyyRjyB1mE0DgEMSnqVof6W1M

install:
- dotnet tool install -g Wyam.Tool
- sudo apt install zip unzip

build_script:
  - bash build-new.sh
  
after_build:
  - ps: Compress-Archive -Path ./output/ -DestinationPath ./output.zip
  - bash upload-netlify.sh
